services:
    database:
        image: postgres:latest
        restart: always
        ports:
          - "6543:5432"
        volumes:
          - pgdata:/var/lib/postgresql/data
        environment:
          POSTGRES_USER: docverse
          POSTGRES_PASSWORD: 8RGvWWodSBPOmQvAvJhEjzu9qVX9kJXN
          POSTGRES_DB: docverse
        networks:
          - docverse
    dashboard:
        env_file: .env
        restart: always
        build:
          context: .
          dockerfile: Dockerfile
        depends_on:
          - database
        ports:
            - '3005:3005'
        networks:
            - docverse

volumes:
    pgdata:

networks:
    docverse:
