services:
    database:
        image: postgres:latest
        restart: always
        ports:
          - "6543:5432"
        volumes:
          - pgdata:/var/lib/postgresql/data
        environment:
          POSTGRES_USER: docverse
          POSTGRES_PASSWORD: 8RGvWWodSBPOmQvAvJhEjzu9qVX9kJXN
          POSTGRES_DB: docverse
        networks:
          - docverse
    dashboard:
        env_file: .env
        restart: always
        build:
          context: .
          dockerfile: Dockerfile
        depends_on:
          - database
        ports:
            - '3005:3005'
        networks:
            - docverse
    
    minio:
      image: minio/minio:latest
      restart: always
      environment:
        MINIO_ROOT_USER: "docverse"
        MINIO_ROOT_PASSWORD: "kQidDcMBGF7yooWZ6Ox9J0gsgZI="
      ports:
        - "9000:9000"
        - "9001:9001"
      command: server /data --console-address ":9001"
      volumes:
        - miniodata:/data
      networks:
        - docverse
      

volumes:
    pgdata:
    miniodata:

networks:
    docverse:
