services:
    database:
        image: postgres:latest
        restart: always
        ports:
          - "6543:5432"
        volumes:
          - pgdata:/var/lib/postgresql/data
          - ./pg-init-scripts:/docker-entrypoint-initdb.d
        environment:
          POSTGRES_USER: docverse
          POSTGRES_PASSWORD: 8RGvWWodSBPOmQvAvJhEjzu9qVX9kJXN
          POSTGRES_MULTIPLE_DATABASES: docverse
        networks:
          - docverse
    dashboard:
        env_file: .env
        restart: always
        build:
          context: .
          dockerfile: Dockerfile
        ports:
            - '3005:3005'
        networks:
            - docverse

networks:
    docverse:
